spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore?currentSchema=bookstore
    username: bookstore
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: bookstore
    liquibase-schema: bookstore

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.saida.bookstore: INFO