spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: bookstore
    password: password
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.saida.bookstore: INFO